server:
  port: ${PORT:0}

spring:
  
  application:
    name: ms-cart
    
#  profiles:
#    active:
#    - default
    
  config:
    import:
    - configserver:${CONFIG_SERVER:http://ms-config-server:8888}
    - vault://
    
  cloud:
  
    config:
      enabled: true
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}
      
    vault:
      enabled: true
      uri: ${VAULT:http://vault:8200}
      authentication: token
      token: ${VAULT_TOKEN:00000000-0000-0000-0000-000000000000}
      
    bus:
      enabled: true
      destination: springCloudBus
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-cart
    username: sa
    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
        '[event.merge.entity_copy_observer]': allow
    show-sql: true
  sql:
    init:
      mode: always
      platform: h2
      
  boot:
    admin:
      client:
        enabled: true
        url: http://ms-sba-server:8086
        username: ${SBA_SERVER_USERNAME:admin}
        password: ${SBA_SERVER_PASSWORD:admin}
        
  zipkin:
    enabled: true
    #base-url: http://zipkin:9411
    sender:
      type: kafka
    kafka:
      topic: zipkin
  
  kafka:
    bootstrap-servers:
    - zipkin-kafka:19092
    
#configuracion para usar rabbitmq en lugar de kafka en cloud bus
#  rabbitmq:
#    host: rabbitmq
#    port: 5672
#    username: rabbitmq
#    password: 123456

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak:8181/auth/realms/msi
    
springdoc:

  title: "Cart Api"
  description: "Api for cart"
  version: "v1.0.0"
  contact-name: "Christian Carranza"
  contact-email: "carranzachristian61@gmail.com"
  contact-url: "https://christiancarranza.com"
  
  api-docs:
    path: /api-docs
#  packages-to-scan:
#  - com.carranzac.application.rest
#  paths-to-match:
#  - /v1
  swagger-ui:
    path: /swagger-ui.html
#    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: true
#    service-url:
#      defaultZone: http://admin:admin@ms-discovery-server:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      product:
        base-config: defecto
    
configuration:
    texto: Configurando entorno interno...