server:
  port: ${PORT:0}
spring:
  
  application:
    name: ms-security-server
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql-security:3306/db_segurity?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '123456'
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:ms-security-server
#    username: sa
#    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
    show-sql: true

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://ms-discovery-server:8761/eureka

jwt:
  key: jwtKey#SuperSecret$JavaMicroservices#
  expirationTimeMinutes: 5